language: java

before_install:
- wget -c http://ftp.unicamp.br/pub/apache/maven/maven-3/3.2.2/binaries/apache-maven-3.2.2-bin.tar.gz
  && mkdir maven && tar xzvf apache-maven-3.2.2-bin.tar.gz -C maven/
- git clone -b maven `git config --get remote.origin.url` target/maven
- cp target/maven/settings.xml ~/.m2/

jdk:
  - oraclejdk7
  - openjdk6

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master

